spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nequi
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
